// Code generated by protoc-gen-gogo.
// source: verify.proto
// DO NOT EDIT!

/*
Package verify_pb is a generated protocol buffer package.

It is generated from these files:
	verify.proto

It has these top-level messages:
	VerifyAsk
	Verify
*/
package verify_pb

import proto "gx/ipfs/QmZ4Qi3GaRbjcx28Sme5eMH7RQjGkt8wHxt2a65oLaeFEV/gogo-protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type VerifyAsk struct {
	Random           *string `protobuf:"bytes,1,opt,name=random" json:"random,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *VerifyAsk) Reset()         { *m = VerifyAsk{} }
func (m *VerifyAsk) String() string { return proto.CompactTextString(m) }
func (*VerifyAsk) ProtoMessage()    {}

func (m *VerifyAsk) GetRandom() string {
	if m != nil && m.Random != nil {
		return *m.Random
	}
	return ""
}

type Verify struct {
	Txid       *string `protobuf:"bytes,1,opt,name=txid" json:"txid,omitempty"`
	Voutid     *int32  `protobuf:"varint,2,opt,name=voutid" json:"voutid,omitempty"`
	Period     *int64  `protobuf:"varint,3,opt,name=period" json:"period,omitempty"`
	Pubkey     *string `protobuf:"bytes,4,opt,name=pubkey" json:"pubkey,omitempty"`
	License    *string `protobuf:"bytes,5,opt,name=license" json:"license,omitempty"`
	Licversion *int32  `protobuf:"varint,6,opt,name=licversion" json:"licversion,omitempty"`
	// 为避免发送方始终使用相同的内容进行签名来代表自己身份，这里要求服务端提供的随机内容进行签名来验证身份
	RandomSign       *string `protobuf:"bytes,7,opt,name=randomSign" json:"randomSign,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Verify) Reset()         { *m = Verify{} }
func (m *Verify) String() string { return proto.CompactTextString(m) }
func (*Verify) ProtoMessage()    {}

func (m *Verify) GetTxid() string {
	if m != nil && m.Txid != nil {
		return *m.Txid
	}
	return ""
}

func (m *Verify) GetVoutid() int32 {
	if m != nil && m.Voutid != nil {
		return *m.Voutid
	}
	return 0
}

func (m *Verify) GetPeriod() int64 {
	if m != nil && m.Period != nil {
		return *m.Period
	}
	return 0
}

func (m *Verify) GetPubkey() string {
	if m != nil && m.Pubkey != nil {
		return *m.Pubkey
	}
	return ""
}

func (m *Verify) GetLicense() string {
	if m != nil && m.License != nil {
		return *m.License
	}
	return ""
}

func (m *Verify) GetLicversion() int32 {
	if m != nil && m.Licversion != nil {
		return *m.Licversion
	}
	return 0
}

func (m *Verify) GetRandomSign() string {
	if m != nil && m.RandomSign != nil {
		return *m.RandomSign
	}
	return ""
}

func init() {
	proto.RegisterType((*VerifyAsk)(nil), "verify.pb.VerifyAsk")
	proto.RegisterType((*Verify)(nil), "verify.pb.Verify")
}
